### ISSUE TITLE
Event Label not being created correctly due to IEnumerable property value for Checkboxes

### ISSUE THREAD

**Issue by alanmac** [codelaborators-network/Google-Analytics-Events-for-Umbraco#12]
Hi folks,

I'm not sure if this is a recent Umbraco change that's causing this (I'm using 7.6.5), but I noticed that the event label that is being contructed is a string representation of IEnumerable because in Events.cs the Label property retrieves the googleAnalyticsEvent_Label from the Umbraco backoffice as a <string. This works fine for the Advanced Event Item as that is a string datatype, but results in an incorrect value being returned for the Standard Event Items that use Checkboxes to build up the label, these return an IEnumerable.

You can see what I mean in the attached images.

I've sent a PR for you to review that solves the issue for me.

![1-events-cs-1](https://user-images.githubusercontent.com/1780374/31522328-28111dac-afa5-11e7-838e-e67a650903ff.PNG)
![2-events-cs-2](https://user-images.githubusercontent.com/1780374/31522331-292c6b2e-afa5-11e7-91cd-6ea6d721975b.PNG)
![3-events-cs-3](https://user-images.githubusercontent.com/1780374/31522333-2aa19768-afa5-11e7-886f-fc70b0b67efd.PNG)
![4-events-json](https://user-images.githubusercontent.com/1780374/31522339-2bf57152-afa5-11e7-8fb5-157298abbd1a.PNG)

**Comment by alanmac** [comment]
My guess is this is happening because of the of the Property Value Converters that were added to the core.

**Comment by prjseal** [comment]
Hi thanks for this. I noticed it was an issue myself on my own site, so I was going to look into it soon.
Thanks for submitting the PR, I will review it and speak to Luke about updating the package.

Paul

**Comment by alanmac** [comment]
No problem Paul, I also have a PR to make the package work with Google Tag Manager. Will send it your way.

Alan

**Comment by Lukejkw** [comment]
@alanmac 

Good find!  Thanks for your continued contributions back to the project.

I'll chat to Paul about getting your PRs merged in

**Comment by alanmac** [comment]
np @Lukejkw 

cheers

**Comment by Lukejkw** [comment]
#13
